### ISSUE TITLE
ErrorCaptureStackTrace(err)

### ISSUE THREAD

**Issue by Cr0w1ey** [govizlora/optical-breacher#33]
I'm sure I'm doing something wrong, but when setting up optical-breacher in my Docker environment on a Pi (linux/arm/v7), I get the following error:

```
yarn run v1.22.5,
$ webpack serve --open,
<i> [webpack-dev-server] Generating SSL Certificate,
(node:28) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.,
(Use `node --trace-deprecation ...` to show where the warning was created),
<i> [webpack-dev-server] Project is running at https://172.17.0.8:1234/,
<i> [webpack-dev-server] Content not from webpack is served from /home/node/app,
<i> [webpack-dev-server] 404s will fallback to /index.html,
node:internal/errors:456,
    ErrorCaptureStackTrace(err);,
    ^,
,
Error: ENOSPC: System limit for number of file watchers reached, watch '/home/node/app/node_modules/enquirer/lib/placeholder.js',
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19),
    at Object.watch (node:fs:2237:34),
    at createFsWatchInstance (/home/node/app/node_modules/chokidar/lib/nodefs-handler.js:119:15),
    at setFsWatchListener (/home/node/app/node_modules/chokidar/lib/nodefs-handler.js:166:15),
    at NodeFsHandler._watchWithNodeFs (/home/node/app/node_modules/chokidar/lib/nodefs-handler.js:331:14),
    at NodeFsHandler._handleFile (/home/node/app/node_modules/chokidar/lib/nodefs-handler.js:395:23),
    at NodeFsHandler._addToNodeFs (/home/node/app/node_modules/chokidar/lib/nodefs-handler.js:628:21),
Emitted 'error' event on FSWatcher instance at:,
    at FSWatcher._handleError (/home/node/app/node_modules/chokidar/index.js:641:10),
    at NodeFsHandler._addToNodeFs (/home/node/app/node_modules/chokidar/lib/nodefs-handler.js:636:18) {,
  errno: -28,,
  syscall: 'watch',,
  code: 'ENOSPC',,
  path: '/home/node/app/node_modules/enquirer/lib/placeholder.js',,
  filename: '/home/node/app/node_modules/enquirer/lib/placeholder.js',
},
error Command failed with exit code 1.,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It's not the end of the world, I just figured I could put the load internally rather than having to go out to the 'net each time I try to breach. Thank you for your wonderful tool!!

**Comment by marksman4103** [comment]
I’m not sure mate I’ll have a look

**Comment by marksman4103** [comment]
1 open website in chrome. 2 click 3 dot icon in top right corner of the
browser. 3 choose add to home and push confirm to install to Home Screen

**Comment by Cr0w1ey** [comment]
Thanks for the advice, but I think you might've misunderstood the issue? I'm not installing the app as a PWA; I'm trying to run it locally on a docker instance so I can self-host it.

**Comment by govizlora** [comment]
Seems related to file update watching from webpack dev server. It might have some compatiblity issue with your system. You should search `System limit for number of file watchers reached` for more info.

Meanwhile, if you don't need the real time watch, you can also run `yarn build` once then host the website using other tools such as [http-server](https://www.npmjs.com/package/http-server) or nginx

**Comment by Cr0w1ey** [comment]
Many thanks for the info. I'll keep plugging away at it and feed back if I get to the bottom of it. So far, https://github.com/awslabs/amazon-eks-ami/issues/501 seems to be an interesting lead.

**Comment by marksman4103** [comment]
You using node

**Comment by marksman4103** [comment]
If idk my hubbies back from Afghanistan sometime next year he’s the brains

**Comment by marksman4103** [comment]
You must use node and yarn but sometimes it miss reads becauseA-B-C-D was dummied by e in E-A-B-C-D which sometimes misread 55 as 5 or 55 as 1c it’s under 50% chance without the dimmie

**Comment by marksman4103** [comment]
Sorry 50% hit chance without added dummie
